// src/components/WebLink.tsx
import clsx from "clsx"
import Image, { type ImageProps } from "next/image"
import path from "node:path"

import { getLinkPreview } from "@/lib/server/link-preview";

const variants = {
  slate: {
    border: 'border-slate-200 hover:border-slate-300',
    title: 'text-slate-800',
    description: 'text-slate-500',
  },
  gray: {
    border: 'border-gray-200 hover:border-gray-300',
    title: 'text-gray-800',
    description: 'text-gray-500',
  },
  green: {
    border: 'border-green-200 hover:border-green-300',
    title: 'text-green-800',
    description: 'text-green-500',
  },
  red: {
    border: 'border-red-200 hover:border-red-300',
    title: 'text-red-800',
    description: 'text-red-500',
  },
  blue: {
    border: 'border-blue-200 hover:border-blue-300',
    title: 'text-blue-800',
    description: 'text-blue-500',
  },
  yellow: {
    border: 'border-yellow-200 hover:border-yellow-300',
    title: 'text-yellow-800',
    description: 'text-yellow-500',
  },
  purple: {
    border: 'border-purple-200 hover:border-purple-300',
    title: 'text-purple-800',
    description: 'text-purple-500',
  },
}

export interface WebLinkPreviewProps {
  href: string
  title?: string
  description?: string | false
  className?: string
  rel?: string
  variant?: keyof typeof variants
  image?: Pick<ImageProps, 'src' | 'alt'> | false
  icon?: Pick<ImageProps, 'src' | 'alt'> | false
}

export async function WebLinkFetchBlock({
  href,
  dirname,
  filename,
  title,
  description,
  rel,
  className,
  variant = 'slate',
  image,
  icon,
}: {
  href: WebLinkPreviewProps['href']
  dirname: string
  filename: string
  title?: WebLinkPreviewProps['title']
  description?: WebLinkPreviewProps['description']
  className?: WebLinkPreviewProps['className']
  rel?: WebLinkPreviewProps['rel']
  variant?: WebLinkPreviewProps['variant']
  image?: false
  icon?: false
}) {
  const preview = await getLinkPreview(href, path.join(dirname.replace('/.next/server/', '/src/'), filename))

  return (
    <WebLinkPreviewBlock
      href={href}
      title={title ?? preview?.title}
      description={description ?? preview?.description}
      image={image ?? (preview?.image ? { src: preview.image, alt: preview.title ?? '' } : undefined)}
      icon={icon ?? (preview?.favicon ? { src: preview.favicon, alt: preview.siteName ?? '' } : undefined)}
      className={className} rel={rel} variant={variant} />
  )
}

export function getSocialLinkIcon(src: string): WebLinkPreviewProps['icon'] {
  switch (src) {
    case 'GITHUB': return { src: '/link-icons/github.svg', alt: 'GitHub' }
    case 'NPM': return { src: '/link-icons/npm.png', alt: 'NPM' }
    default: return undefined
  }
}

export function WebLinkPreviewBlock({
  href,
  title,
  description,
  rel,
  className,
  variant = 'slate',
  image,
  icon,
}: WebLinkPreviewProps) {
  return (
    <a
      href={href}
      target="_blank"
      rel={rel ?? 'nofollow noopener noreferrer'}
      className={clsx(
        'group block w-full max-w-3xl my-5 overflow-hidden rounded-2xl border bg-white not-prose shadow-sm transition hover:shadow',
        variants[variant].border,
        className,
      )}
    >
      <div className="flex flex-col sm:flex-row min-h-[120px]">
        {/* Bottom/Left content */}
        <div className="flex flex-1 flex-col min-w-0 gap-2 px-5 py-4 order-2 sm:order-1">
          {title && (
            <span className={clsx('text-[18px] font-bold leading-snug', variants[variant].title)}>
              {title}
            </span>
          )}

          {description && (
            <p className="text-[15px] leading-snug">
              {description}
            </p>
          )}

          <div className="mt-auto flex items-center gap-2">
            {icon && (
              <Image
                src={icon.src}
                alt={icon.alt}
                className="h-5 w-5 flex-none rounded-sm"
                loading="lazy"
                height={10}
                width={10}
              />
            )}

            <span className="min-w-0 truncate text-[15px] font-light">
              {href.replace(/^http(s)?:\/\//, '').replace(/^www./, '')}
            </span>
          </div>
        </div>

        {/* Top/Right image */}
        {image && (
          <div className="relative sm:w-[36%] sm:min-w-[220px] sm:max-w-[340px] flex-none order-1 sm:order-2">
            <Image
              src={image.src}
              alt={image.alt}
              className="h-full w-full max-h-[250px] sm:max-h-full object-cover"
              loading="lazy"
              height={200}
              width={200}
            />
          </div>
        )}
      </div>
    </a>
  )
}

// .vitepress/theme/components/WebLink.vue
<script setup lang="ts">
const props = withDefaults(defineProps<{
  href: string;
  title?: string;
  description?: string;
  variant?: string;
  image?: string;
  icon?: string;
  iconAlt?: string;
}>(), {
  variant: 'slate',
});

const domain = props.href.replace(/^https?:\/\//, '').replace(/^www\./, '');
</script>

<template>
  <a :href="href" target="_blank" rel="nofollow noopener noreferrer" :class="[
    'group block w-full max-w-3xl my-5 overflow-hidden rounded-2xl border bg-white not-prose shadow-sm transition hover:shadow',
    `border-${variant}-200 hover:border-${variant}-300`,
  ]">
    <div class="flex flex-col sm:flex-row min-h-[120px]">
      <div class="flex flex-1 flex-col min-w-0 gap-2 px-5 py-4 order-2 sm:order-1">
        <span v-if="title" :class="[`text-[18px] font-bold leading-snug text-${variant}-800`]">{{ title }}</span>
        <p v-if="description" class="text-[15px] leading-snug">{{ description }}</p>
        <div class="mt-auto flex items-center gap-2">
          <img v-if="icon" :src="icon" :alt="iconAlt" class="h-5 w-5 flex-none rounded-sm" loading="lazy" height="10" width="10">
          <span class="min-w-0 truncate text-[15px] font-light">{{ domain }}</span>
        </div>
      </div>
      <div v-if="image" class="relative sm:w-[36%] sm:min-w-[220px] sm:max-w-[340px] flex-none order-1 sm:order-2">
        <img :src="image" :alt="title" class="h-full w-full max-h-[250px] sm:max-h-full object-cover" loading="lazy" height="200" width="200">
      </div>
    </div>
  </a>
</template>
